#!/command/with-contenv sh

if [ -z "$RAILS_MASTER_KEY" ]; then
  echo "!!!!!!!!!!!!!!! WORKER ERROR !!!!!!!!!!!!!!!!!!!"
  echo "! Missing RAILS_MASTER_KEY, Set it and keep it !"
  echo "! safe to dencrypt storaged data in database   !"
  echo "!!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!!!!"
else
  echo "Launching Subway Worker Service"
  cd /app && bin/good_job start
fi
