#!/command/with-contenv sh

if [ -z "$RAILS_MASTER_KEY" ]; then
  echo "!!!!!!!!!!!!!!!! Web ERROR !!!!!!!!!!!!!!!!!!!!!"
  echo "! Missing RAILS_MASTER_KEY, Set it and keep it !"
  echo "! safe to dencrypt storaged data in database   !"
  echo "!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!!!!!!"
else
  cd /app

  echo "Launching Subway Web Server"
  bin/puma -C config/puma.rb | tee log/production.log
fi
