#!/command/with-contenv sh

cd /app

# Clear pid if unexpected exception exit
rm -f tmp/pids/.pid

# Remove legacy encrypted file
rm -f config/credentials.yml.enc

# Create project requires directory
mkdir -p tmp/pids tmp/cache tmp/uploads tmp/sockets log config/credentials

bin/rails subway:credentials
bin/rails subway:upgrade

exit 0
