ARG VARIANT=3.2.2
FROM ruby:${VARIANT}
LABEL org.opencontainers.image.title="Subway" \
      org.opencontainers.image.authors="0x5c3p73r <0x5c3p73r@gmail.com>" \
      org.opencontainers.image.source="https://github.com/0x5c3p73r/subway"

# Install ruby on rails dependencies:
ARG BUILD_PACKAGES="libpq-dev yarnpkg git zlib1g-dev build-essential libssl-dev libreadline-dev \
                    libyaml-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev \
                    software-properties-common libffi-dev"
ARG PROJECT_PACKAGES="sudo tar ca-certificates tzdata git zsh curl watchman postgresql-client"

ARG ENABLE_DEBIAN_MIRROR="true"
ARG ORIGINAL_REPO_URL="deb.debian.org"
ARG MIRROR_REPO_URL="mirrors.ustc.edu.cn"
ARG RUBYGEMS_SOURCE="https://gems.ruby-china.com/"
ARG RUBY_GEMS="bundler:2.4.21 solargraph foreman"

# System dependencies
RUN set -ex && \
    if [[ "$ENABLE_DEBIAN_MIRROR" == "true" ]]; then \
      sed -i "s/$ORIGINAL_REPO_URL/$MIRROR_REPO_URL/g" /etc/apt/sources.list.d/debian.sources && \
      gem sources --add $RUBYGEMS_SOURCE --remove https://rubygems.org/ && \
      bundle config mirror.https://rubygems.org $RUBYGEMS_SOURCE; \
    fi && \
    apt-get update -qq && apt-get install -y $BUILD_PACKAGES $PROJECT_PACKAGES && \
    gem install -N $RUBY_GEMS

ENV RAILS_ENV="development"

# Setup workspace
WORKDIR /workspace

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3

COPY . /workspace
