version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
      SUBWAY_BACKEND_NAME: "local-subconverter-service"
      SUBWAY_BACKEND_URL: http://localhost:25500

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    network_mode: service:db

  subconverter:
    restart: unless-stopped
    image: tindy2013/subconverter
    network_mode: service:db

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    network_mode: service:db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@localhost/postgres"

volumes:
  postgres-data:
