version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev

    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      LOCAL_BACKEND_URL: http://subconverter

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # network_mode: service:db

  subconverter:
    restart: unless-stopped
    image: tindy2013/subconverter

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    network_mode: service:db

volumes:
  postgres-data:
