#!/command/with-contenv bash
# shellcheck shell=bash

if [ -z "$RAILS_MASTER_KEY" ]; then
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "! Missing RAILS_MASTER_KEY, Set it and keep it safe !"
  echo "! to dencrypt storaged data in database.            !"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  exit 1
fi

if [ -z "$RAILS_ENCRYPTED_DATA" ] && [ -f "/app/config/" ]; then
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "! Missing RAILS_ENCRYPTED_DATA or not found the     !"
  echo "! credentials file in config folder.                !"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  exit 1
fi

cd /app

# Clear pid if unexpected exception exit
rm -f tmp/pids/.pid

# Remove legacy encrypted file
rm -f config/credentials.yml.enc

# Create project requires directory
mkdir -p tmp/pids tmp/cache tmp/uploads tmp/sockets log config/credentials

bin/rails subway:credentials
bin/rails subway:upgrade

exit 0
