#!/command/with-contenv bash
# shellcheck shell=bash

cat /etc/s6-overlay/s6-rc.d/setup-timezone/branding

TZ=${TZ:-"Asia/Shanghai"}

if [ -f "/usr/share/zoneinfo/$TZ" ]; then
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
  echo "$TZ" > /etc/timezone
fi

exit 0
