name: Publish Deploy-ready Docker Image
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
    paths-ignore:
      - '.devcontainer/*'
      - '.github/workflows/publish_codespace_image.yml*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GIT_REF: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker Build Date
        id: build_date
        run: echo "::set-output name=value::$(date +'%Y-%m-%d')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: |
            ${{ steps.metadata.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build_date.outputs.value }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=docker-build-release
          cache-to: type=gha,mode=max,scope=docker-build-release
          build-args: |
            REPLACE_CHINA_MIRROR=false
          secrets: |
            "master_key=${{ secrets.COMPLIE_ASSETS_MASTER_KEY }}"
            "credentials_data=${{ secrets.COMPLIE_ASSETS_CREDENTIALS_DATA }}"
